/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 /home/obx/Documents/Work/Graphics/sprite.glb -o /home/obx/Documents/Work/Graphics/sprite.tsx --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['GEO-sprite_capmelted_chunk']: THREE.Mesh
    ['Data_GEO-sprite_teeth_btm_sharp']: THREE.Mesh
    ['Data_GEO-sprite_teeth_btm_sharp_1']: THREE.Mesh
    ['Data_GEO-sprite_teeth_top_sharp']: THREE.Mesh
    ['Data_GEO-sprite_teeth_top_sharp_1']: THREE.Mesh
    ['Data_GEO-sprite_teeth_btm']: THREE.Mesh
    ['Data_GEO-sprite_teeth_btm_1']: THREE.Mesh
    ['Data_GEO-sprite_teeth_btm_square']: THREE.Mesh
    ['Data_GEO-sprite_teeth_btm_square_1']: THREE.Mesh
    ['Data_GEO-sprite_teeth_top']: THREE.Mesh
    ['Data_GEO-sprite_teeth_top_1']: THREE.Mesh
    ['Data_GEO-sprite_teeth_top_square']: THREE.Mesh
    ['Data_GEO-sprite_teeth_top_square_1']: THREE.Mesh
    ['Data_GEO-sprite_body_head']: THREE.SkinnedMesh
    ['Data_GEO-sprite_body_head_1']: THREE.SkinnedMesh
    ['Data_GEO-sprite_capmelted']: THREE.SkinnedMesh
    ['Data_GEO-sprite_capmelted_1']: THREE.SkinnedMesh
    ['GEO-sprite_diaper']: THREE.SkinnedMesh
    ['GEO-sprite_diaper_alt']: THREE.SkinnedMesh
    ['GEO-sprite_eyebrows']: THREE.SkinnedMesh
    ['GEO-sprite_eyebrowsevil']: THREE.SkinnedMesh
    ['GEO-sprite_eyedotL']: THREE.SkinnedMesh
    ['GEO-sprite_eyedotR']: THREE.SkinnedMesh
    ['GEO-sprite_teeth_bot_deformer']: THREE.SkinnedMesh
    ['GEO-sprite_teeth_top_deformer']: THREE.SkinnedMesh
    ['GEO-sprite_tongue']: THREE.SkinnedMesh
    ['GEO-sprite_body_arms']: THREE.SkinnedMesh
    ['GEO-sprite_body_head_rig_helper']: THREE.SkinnedMesh
    ['GEO-sprite_body_legs']: THREE.SkinnedMesh
    ['GEO-sprite_body_torso']: THREE.SkinnedMesh
    ['Data_GEO-sprite_cap']: THREE.SkinnedMesh
    ['Data_GEO-sprite_cap_1']: THREE.SkinnedMesh
    ['Data_GEO-sprite_eyeL']: THREE.SkinnedMesh
    ['Data_GEO-sprite_eyeL_1']: THREE.SkinnedMesh
    ['Data_GEO-sprite_eyeR']: THREE.SkinnedMesh
    ['Data_GEO-sprite_eyeR_1']: THREE.SkinnedMesh
    ['GEO-sprite_body_headeyes_closed']: THREE.Mesh
    Spine: THREE.Bone
    ['PRP-Head']: THREE.Bone
    ['P-GrabL']: THREE.Bone
    Properties_Character_Sprite: THREE.Bone
    Eyelid_Lower1L: THREE.Bone
    Eyelid_Upper1L: THREE.Bone
    ['ROOT-EarL']: THREE.Bone
    ['P-ACT-MouthCornerL']: THREE.Bone
    Teeth_Top_Root: THREE.Bone
    OuterLip_Upper2L: THREE.Bone
    OuterLip_Upper1L: THREE.Bone
    OuterLip_Upper: THREE.Bone
    ['P-CTR-CheekPuffL']: THREE.Bone
    Cheek1L: THREE.Bone
    ['STR-Head_Top']: THREE.Bone
    ['STR-I-Lip_Bottom1']: THREE.Bone
    ['STR-I-Lip_Top1']: THREE.Bone
    ['P-GrabR']: THREE.Bone
    Eyelid_Lower1R: THREE.Bone
    Eyelid_Upper1R: THREE.Bone
    ['ROOT-EarR']: THREE.Bone
    ['P-ACT-MouthCornerR']: THREE.Bone
    OuterLip_Upper2R: THREE.Bone
    OuterLip_Upper1R: THREE.Bone
    ['P-CTR-CheekPuffR']: THREE.Bone
    Cheek1R: THREE.Bone
    ['P-Empty1L']: THREE.Bone
    ['P-Empty1R']: THREE.Bone
    ['P-Empty2L']: THREE.Bone
    ['P-Empty2R']: THREE.Bone
    ['LTC-MeltingCap1']: THREE.Bone
    ['LTC-MeltingCap3']: THREE.Bone
    ['LTC-MeltingCap2']: THREE.Bone
    ['P-root']: THREE.Bone
    ['STR-TIP-P-Eyelid_Lower4L']: THREE.Bone
    ['STR-P-Eyelid_Lower4L']: THREE.Bone
    ['STR-P-Eyelid_Lower3L']: THREE.Bone
    ['STR-P-Eyelid_Lower2L']: THREE.Bone
    ['STR-P-Eyelid_Lower1L']: THREE.Bone
    ['STR-TIP-P-Eyelid_Upper4L']: THREE.Bone
    ['STR-P-Eyelid_Upper4L']: THREE.Bone
    ['STR-P-Eyelid_Upper3L']: THREE.Bone
    ['STR-P-Eyelid_Upper2L']: THREE.Bone
    ['STR-P-Eyelid_Upper1L']: THREE.Bone
    ['ROOT-EarL_1']: THREE.Bone
    ['STR-P-Ear3L']: THREE.Bone
    ['STR-P-Ear2L']: THREE.Bone
    HeadSide1L: THREE.Bone
    ['P-ACT-MouthCornerL_1']: THREE.Bone
    Teeth_Top_Root_1: THREE.Bone
    ['STR-I-P-Teeth_Upper2']: THREE.Bone
    ['STR-P-Teeth_Upper2L']: THREE.Bone
    ['STR-P-Teeth_Upper1L']: THREE.Bone
    ['STR-P-Teeth_Upper2R']: THREE.Bone
    ['STR-P-Teeth_Upper1R']: THREE.Bone
    OuterLip_Upper2L_1: THREE.Bone
    OuterLip_Upper1L_1: THREE.Bone
    OuterLip_Upper_1: THREE.Bone
    ['P-CTR-CheekPuffL_1']: THREE.Bone
    ['ROOT-LTC-Cheek1L']: THREE.Bone
    ['STR-TIP-P-Eyelid_Lower4R']: THREE.Bone
    ['STR-P-Eyelid_Lower4R']: THREE.Bone
    ['STR-P-Eyelid_Lower3R']: THREE.Bone
    ['STR-P-Eyelid_Lower2R']: THREE.Bone
    ['STR-P-Eyelid_Lower1R']: THREE.Bone
    ['STR-TIP-P-Eyelid_Upper4R']: THREE.Bone
    ['STR-P-Eyelid_Upper4R']: THREE.Bone
    ['STR-P-Eyelid_Upper3R']: THREE.Bone
    ['STR-P-Eyelid_Upper2R']: THREE.Bone
    ['STR-P-Eyelid_Upper1R']: THREE.Bone
    ['ROOT-EarR_1']: THREE.Bone
    ['STR-P-Ear3R']: THREE.Bone
    ['STR-P-Ear2R']: THREE.Bone
    HeadSide1R: THREE.Bone
    ['P-ACT-MouthCornerR_1']: THREE.Bone
    OuterLip_Upper2R_1: THREE.Bone
    OuterLip_Upper1R_1: THREE.Bone
    ['P-CTR-CheekPuffR_1']: THREE.Bone
    ['ROOT-LTC-Cheek1R']: THREE.Bone
    ['P-P-Empty1L']: THREE.Bone
    ['P-P-Empty1R']: THREE.Bone
    ['P-P-Empty2L']: THREE.Bone
    ['P-P-Empty2R']: THREE.Bone
    ['P-P-GrabL']: THREE.Bone
    ['P-P-GrabR']: THREE.Bone
    ['P-ROOT-P-UpperArmL']: THREE.Bone
    ['DSP-AutoRubberHose-ForearmL']: THREE.Bone
    ['FK-HNG-UpperArmL']: THREE.Bone
    ['P-ROOT-P-UpperArmR']: THREE.Bone
    ['DSP-AutoRubberHose-ForearmR']: THREE.Bone
    ['FK-HNG-UpperArmR']: THREE.Bone
    ['ACT-P-Eyelid_LowerL']: THREE.Bone
    ['ACT-P-Eyelid_LowerR']: THREE.Bone
    ['ACT-P-Eyelid_UpperL']: THREE.Bone
    ['ACT-P-Eyelid_UpperR']: THREE.Bone
    ['P-Cheek2_4L']: THREE.Bone
    ['P-Cheek2_4R']: THREE.Bone
    ['ROOT-P-EyeL']: THREE.Bone
    ['P-MSTR-TGT-Eyes']: THREE.Bone
    ['ROOT-P-EyeR']: THREE.Bone
    ['P-Eyebrow_Mid']: THREE.Bone
    Eyebrow_Mid: THREE.Bone
    ['P-ForeheadRing']: THREE.Bone
    ['P-ForeheadRing1L']: THREE.Bone
    ['P-ForeheadRing1R']: THREE.Bone
    ['P-ForeheadRing2L']: THREE.Bone
    ['P-ForeheadRing2R']: THREE.Bone
    ['P-HeadSide2L']: THREE.Bone
    ['P-HeadSide2R']: THREE.Bone
    ['LTC-P-Mask_Root']: THREE.Bone
    ['LTC-P-UpperEyelidL']: THREE.Bone
    ['LTC-P-UpperEyelidR']: THREE.Bone
    ['MSTR-P-EyebrowL']: THREE.Bone
    BrowRing3L: THREE.Bone
    BrowRing1L: THREE.Bone
    ['DT-Eyebrow2L']: THREE.Bone
    ['DT-Eyebrow4L']: THREE.Bone
    ['MSTR-P-EyebrowR']: THREE.Bone
    BrowRing3R: THREE.Bone
    BrowRing1R: THREE.Bone
    ['DT-Eyebrow2R']: THREE.Bone
    ['DT-Eyebrow4R']: THREE.Bone
    ['P-NoseBridge1']: THREE.Bone
    ['P-Nose_Mid']: THREE.Bone
    ['ROOT-P-Evil_EyebrowL']: THREE.Bone
    ['ROOT-Evil_EyebrowL']: THREE.Bone
    ['ROOT-P-Evil_EyebrowR']: THREE.Bone
    ['ROOT-Evil_EyebrowR']: THREE.Bone
    ['STR-I-P-Cap_Base_Front+Edge1']: THREE.Bone
    ['STR-I-P-Cap_Edge2+Base_Back']: THREE.Bone
    ['STR-I-P-Cap_Base+Edge2L']: THREE.Bone
    ['STR-I-P-Cap_Base+Edge2R']: THREE.Bone
    ['P-Cheek2_3L']: THREE.Bone
    Cheek2_3L: THREE.Bone
    ['P-Cheek2_3R']: THREE.Bone
    Cheek2_3R: THREE.Bone
    ['P-Nose_Root']: THREE.Bone
    ['MSTR-P-Head_Bottom']: THREE.Bone
    ['P-STR-I-Lip_Bottom1']: THREE.Bone
    ['P-STR-Lip_Bottom1L']: THREE.Bone
    ['P-STR-Lip_Bottom1R']: THREE.Bone
    ['CTR-LipCornerL']: THREE.Bone
    ['P-STR-TIP-Lip_Top2L']: THREE.Bone
    ['P-STR-Lip_Bottom2L']: THREE.Bone
    ['P-STR-I-Lip_Top1']: THREE.Bone
    ['P-STR-Lip_Top2L']: THREE.Bone
    ['CTR-LipCornerR']: THREE.Bone
    ['P-STR-TIP-Lip_Top2R']: THREE.Bone
    ['P-STR-Lip_Bottom2R']: THREE.Bone
    ['P-STR-Lip_Top2R']: THREE.Bone
    ['ROOT-LTC-Lips']: THREE.Bone
    Teeth_Bottom_Root: THREE.Bone
    ['STR-I-P-Teeth_Lower2']: THREE.Bone
    ['STR-P-Teeth_Lower2L']: THREE.Bone
    ['STR-P-Teeth_Lower1L']: THREE.Bone
    ['STR-P-Teeth_Lower2R']: THREE.Bone
    ['STR-P-Teeth_Lower1R']: THREE.Bone
    Bridge_Chin: THREE.Bone
    OuterLip_Lower: THREE.Bone
    Bridge_Chin2_1L: THREE.Bone
    Bridge_Chin1_1L: THREE.Bone
    OuterLip_Lower1L: THREE.Bone
    Cheek3_1L: THREE.Bone
    Chin_Main: THREE.Bone
    JawLine4L: THREE.Bone
    JawLine4R: THREE.Bone
    Bridge_Lower_Chin: THREE.Bone
    Bridge_Chin2_2L: THREE.Bone
    Cheek3_2L: THREE.Bone
    Bridge_Chin1_2L: THREE.Bone
    Bridge_Chin2_1R: THREE.Bone
    Bridge_Chin1_1R: THREE.Bone
    OuterLip_Lower1R: THREE.Bone
    Cheek3_1R: THREE.Bone
    Bridge_Chin2_2R: THREE.Bone
    Cheek3_2R: THREE.Bone
    Bridge_Chin1_2R: THREE.Bone
    ['FK-Tongue1']: THREE.Bone
    ['FK-HNG-Head']: THREE.Bone
    ['P-Toe1L']: THREE.Bone
    ['P-Toe2L']: THREE.Bone
    ['P-Toe3L']: THREE.Bone
    ['P-Toe4L']: THREE.Bone
    ['DSP-AutoRubberHose-KneeL']: THREE.Bone
    ['FK-HNG-ThighL']: THREE.Bone
    ['P-Toe1R']: THREE.Bone
    ['P-Toe2R']: THREE.Bone
    ['P-Toe3R']: THREE.Bone
    ['P-Toe4R']: THREE.Bone
    ['DSP-AutoRubberHose-KneeR']: THREE.Bone
    ['FK-HNG-ThighR']: THREE.Bone
    ['IK-POLE-P-UpperArmL']: THREE.Bone
    ['P-IK-MSTR-WristL']: THREE.Bone
    ['IK-POLE-P-UpperArmR']: THREE.Bone
    ['P-IK-MSTR-WristR']: THREE.Bone
    ['FK-ToesL']: THREE.Bone
    ['IK-POLE-P-ThighL']: THREE.Bone
    ['P-IK-MSTR-FootL']: THREE.Bone
    ['FK-ToesR']: THREE.Bone
    ['IK-POLE-P-ThighR']: THREE.Bone
    ['P-IK-MSTR-FootR']: THREE.Bone
  }
  materials: {
    ['sprite.cap_red.001']: THREE.MeshStandardMaterial
    ['sprite.teeth']: THREE.MeshStandardMaterial
    ['sprite.gums']: THREE.MeshStandardMaterial
    ['sprite.head']: THREE.MeshStandardMaterial
    ['sprite.mouth_inner']: THREE.MeshStandardMaterial
    ['sprite.cap_melted']: THREE.MeshPhysicalMaterial
    ['sprite.cap_inside']: THREE.MeshPhysicalMaterial
    ['sprite.diaper']: THREE.MeshPhysicalMaterial
    ['sprite.skin']: THREE.MeshStandardMaterial
    ['sprite.eyebrows']: THREE.MeshStandardMaterial
    ['sprite.highlights']: THREE.MeshStandardMaterial
    ['sprite.tongue']: THREE.MeshStandardMaterial
    ['sprite.skin.001']: THREE.MeshStandardMaterial
    ['sprite.cap']: THREE.MeshPhysicalMaterial
    ['sprite.eyes']: THREE.MeshStandardMaterial
    ['sprite.pupils']: THREE.MeshStandardMaterial
    ['sprite.skin.001']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { scene } = useGLTF('/sprite.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-0.104, -0.045, -0.046]} scale={1.265}>
        <primitive object={nodes['P-root']} />
        <primitive object={nodes['STR-TIP-P-Eyelid_Lower4L']} />
        <primitive object={nodes['STR-P-Eyelid_Lower4L']} />
        <primitive object={nodes['STR-P-Eyelid_Lower3L']} />
        <primitive object={nodes['STR-P-Eyelid_Lower2L']} />
        <primitive object={nodes['STR-P-Eyelid_Lower1L']} />
        <primitive object={nodes['STR-TIP-P-Eyelid_Upper4L']} />
        <primitive object={nodes['STR-P-Eyelid_Upper4L']} />
        <primitive object={nodes['STR-P-Eyelid_Upper3L']} />
        <primitive object={nodes['STR-P-Eyelid_Upper2L']} />
        <primitive object={nodes['STR-P-Eyelid_Upper1L']} />
        <primitive object={nodes['ROOT-EarL_1']} />
        <primitive object={nodes['STR-P-Ear3L']} />
        <primitive object={nodes['STR-P-Ear2L']} />
        <primitive object={nodes.HeadSide1L} />
        <primitive object={nodes['P-ACT-MouthCornerL_1']} />
        <primitive object={nodes.Teeth_Top_Root_1} />
        <primitive object={nodes['STR-I-P-Teeth_Upper2']} />
        <primitive object={nodes['STR-P-Teeth_Upper2L']} />
        <primitive object={nodes['STR-P-Teeth_Upper1L']} />
        <primitive object={nodes['STR-P-Teeth_Upper2R']} />
        <primitive object={nodes['STR-P-Teeth_Upper1R']} />
        <primitive object={nodes.OuterLip_Upper2L_1} />
        <primitive object={nodes.OuterLip_Upper1L_1} />
        <primitive object={nodes.OuterLip_Upper_1} />
        <primitive object={nodes['P-CTR-CheekPuffL_1']} />
        <primitive object={nodes['ROOT-LTC-Cheek1L']} />
        <primitive object={nodes['STR-TIP-P-Eyelid_Lower4R']} />
        <primitive object={nodes['STR-P-Eyelid_Lower4R']} />
        <primitive object={nodes['STR-P-Eyelid_Lower3R']} />
        <primitive object={nodes['STR-P-Eyelid_Lower2R']} />
        <primitive object={nodes['STR-P-Eyelid_Lower1R']} />
        <primitive object={nodes['STR-TIP-P-Eyelid_Upper4R']} />
        <primitive object={nodes['STR-P-Eyelid_Upper4R']} />
        <primitive object={nodes['STR-P-Eyelid_Upper3R']} />
        <primitive object={nodes['STR-P-Eyelid_Upper2R']} />
        <primitive object={nodes['STR-P-Eyelid_Upper1R']} />
        <primitive object={nodes['ROOT-EarR_1']} />
        <primitive object={nodes['STR-P-Ear3R']} />
        <primitive object={nodes['STR-P-Ear2R']} />
        <primitive object={nodes.HeadSide1R} />
        <primitive object={nodes['P-ACT-MouthCornerR_1']} />
        <primitive object={nodes.OuterLip_Upper2R_1} />
        <primitive object={nodes.OuterLip_Upper1R_1} />
        <primitive object={nodes['P-CTR-CheekPuffR_1']} />
        <primitive object={nodes['ROOT-LTC-Cheek1R']} />
        <primitive object={nodes['P-P-Empty1L']} />
        <primitive object={nodes['P-P-Empty1R']} />
        <primitive object={nodes['P-P-Empty2L']} />
        <primitive object={nodes['P-P-Empty2R']} />
        <primitive object={nodes['P-P-GrabL']} />
        <primitive object={nodes['P-P-GrabR']} />
        <primitive object={nodes['P-ROOT-P-UpperArmL']} />
        <primitive object={nodes['DSP-AutoRubberHose-ForearmL']} />
        <primitive object={nodes['FK-HNG-UpperArmL']} />
        <primitive object={nodes['P-ROOT-P-UpperArmR']} />
        <primitive object={nodes['DSP-AutoRubberHose-ForearmR']} />
        <primitive object={nodes['FK-HNG-UpperArmR']} />
        <primitive object={nodes['ACT-P-Eyelid_LowerL']} />
        <primitive object={nodes['ACT-P-Eyelid_LowerR']} />
        <primitive object={nodes['ACT-P-Eyelid_UpperL']} />
        <primitive object={nodes['ACT-P-Eyelid_UpperR']} />
        <primitive object={nodes['P-Cheek2_4L']} />
        <primitive object={nodes['P-Cheek2_4R']} />
        <primitive object={nodes['ROOT-P-EyeL']} />
        <primitive object={nodes['P-MSTR-TGT-Eyes']} />
        <primitive object={nodes['ROOT-P-EyeR']} />
        <primitive object={nodes['P-Eyebrow_Mid']} />
        <primitive object={nodes.Eyebrow_Mid} />
        <primitive object={nodes['P-ForeheadRing']} />
        <primitive object={nodes['P-ForeheadRing1L']} />
        <primitive object={nodes['P-ForeheadRing1R']} />
        <primitive object={nodes['P-ForeheadRing2L']} />
        <primitive object={nodes['P-ForeheadRing2R']} />
        <primitive object={nodes['P-HeadSide2L']} />
        <primitive object={nodes['P-HeadSide2R']} />
        <primitive object={nodes['LTC-P-Mask_Root']} />
        <primitive object={nodes['LTC-P-UpperEyelidL']} />
        <primitive object={nodes['LTC-P-UpperEyelidR']} />
        <primitive object={nodes['MSTR-P-EyebrowL']} />
        <primitive object={nodes.BrowRing3L} />
        <primitive object={nodes.BrowRing1L} />
        <primitive object={nodes['DT-Eyebrow2L']} />
        <primitive object={nodes['DT-Eyebrow4L']} />
        <primitive object={nodes['MSTR-P-EyebrowR']} />
        <primitive object={nodes.BrowRing3R} />
        <primitive object={nodes.BrowRing1R} />
        <primitive object={nodes['DT-Eyebrow2R']} />
        <primitive object={nodes['DT-Eyebrow4R']} />
        <primitive object={nodes['P-NoseBridge1']} />
        <primitive object={nodes['P-Nose_Mid']} />
        <primitive object={nodes['ROOT-P-Evil_EyebrowL']} />
        <primitive object={nodes['ROOT-Evil_EyebrowL']} />
        <primitive object={nodes['ROOT-P-Evil_EyebrowR']} />
        <primitive object={nodes['ROOT-Evil_EyebrowR']} />
        <primitive object={nodes['STR-I-P-Cap_Base_Front+Edge1']} />
        <primitive object={nodes['STR-I-P-Cap_Edge2+Base_Back']} />
        <primitive object={nodes['STR-I-P-Cap_Base+Edge2L']} />
        <primitive object={nodes['STR-I-P-Cap_Base+Edge2R']} />
        <primitive object={nodes['P-Cheek2_3L']} />
        <primitive object={nodes.Cheek2_3L} />
        <primitive object={nodes['P-Cheek2_3R']} />
        <primitive object={nodes.Cheek2_3R} />
        <primitive object={nodes['P-Nose_Root']} />
        <primitive object={nodes['MSTR-P-Head_Bottom']} />
        <primitive object={nodes['P-STR-I-Lip_Bottom1']} />
        <primitive object={nodes['P-STR-Lip_Bottom1L']} />
        <primitive object={nodes['P-STR-Lip_Bottom1R']} />
        <primitive object={nodes['CTR-LipCornerL']} />
        <primitive object={nodes['P-STR-TIP-Lip_Top2L']} />
        <primitive object={nodes['P-STR-Lip_Bottom2L']} />
        <primitive object={nodes['P-STR-I-Lip_Top1']} />
        <primitive object={nodes['P-STR-Lip_Top2L']} />
        <primitive object={nodes['CTR-LipCornerR']} />
        <primitive object={nodes['P-STR-TIP-Lip_Top2R']} />
        <primitive object={nodes['P-STR-Lip_Bottom2R']} />
        <primitive object={nodes['P-STR-Lip_Top2R']} />
        <primitive object={nodes['ROOT-LTC-Lips']} />
        <primitive object={nodes.Teeth_Bottom_Root} />
        <primitive object={nodes['STR-I-P-Teeth_Lower2']} />
        <primitive object={nodes['STR-P-Teeth_Lower2L']} />
        <primitive object={nodes['STR-P-Teeth_Lower1L']} />
        <primitive object={nodes['STR-P-Teeth_Lower2R']} />
        <primitive object={nodes['STR-P-Teeth_Lower1R']} />
        <primitive object={nodes.Bridge_Chin} />
        <primitive object={nodes.OuterLip_Lower} />
        <primitive object={nodes.Bridge_Chin2_1L} />
        <primitive object={nodes.Bridge_Chin1_1L} />
        <primitive object={nodes.OuterLip_Lower1L} />
        <primitive object={nodes.Cheek3_1L} />
        <primitive object={nodes.Chin_Main} />
        <primitive object={nodes.JawLine4L} />
        <primitive object={nodes.JawLine4R} />
        <primitive object={nodes.Bridge_Lower_Chin} />
        <primitive object={nodes.Bridge_Chin2_2L} />
        <primitive object={nodes.Cheek3_2L} />
        <primitive object={nodes.Bridge_Chin1_2L} />
        <primitive object={nodes.Bridge_Chin2_1R} />
        <primitive object={nodes.Bridge_Chin1_1R} />
        <primitive object={nodes.OuterLip_Lower1R} />
        <primitive object={nodes.Cheek3_1R} />
        <primitive object={nodes.Bridge_Chin2_2R} />
        <primitive object={nodes.Cheek3_2R} />
        <primitive object={nodes.Bridge_Chin1_2R} />
        <primitive object={nodes['FK-Tongue1']} />
        <primitive object={nodes['FK-HNG-Head']} />
        <primitive object={nodes['P-Toe1L']} />
        <primitive object={nodes['P-Toe2L']} />
        <primitive object={nodes['P-Toe3L']} />
        <primitive object={nodes['P-Toe4L']} />
        <primitive object={nodes['DSP-AutoRubberHose-KneeL']} />
        <primitive object={nodes['FK-HNG-ThighL']} />
        <primitive object={nodes['P-Toe1R']} />
        <primitive object={nodes['P-Toe2R']} />
        <primitive object={nodes['P-Toe3R']} />
        <primitive object={nodes['P-Toe4R']} />
        <primitive object={nodes['DSP-AutoRubberHose-KneeR']} />
        <primitive object={nodes['FK-HNG-ThighR']} />
        <primitive object={nodes['IK-POLE-P-UpperArmL']} />
        <primitive object={nodes['P-IK-MSTR-WristL']} />
        <primitive object={nodes['IK-POLE-P-UpperArmR']} />
        <primitive object={nodes['P-IK-MSTR-WristR']} />
        <primitive object={nodes['FK-ToesL']} />
        <primitive object={nodes['IK-POLE-P-ThighL']} />
        <primitive object={nodes['P-IK-MSTR-FootL']} />
        <primitive object={nodes['FK-ToesR']} />
        <primitive object={nodes['IK-POLE-P-ThighR']} />
        <primitive object={nodes['P-IK-MSTR-FootR']} />
        <mesh geometry={nodes['GEO-sprite_capmelted_chunk'].geometry} material={materials['sprite.cap_red.001']} />
        <skinnedMesh geometry={nodes['GEO-sprite_diaper'].geometry} material={materials['sprite.diaper']} skeleton={nodes['GEO-sprite_diaper'].skeleton} />
        <skinnedMesh geometry={nodes['GEO-sprite_diaper_alt'].geometry} material={materials['sprite.skin']} skeleton={nodes['GEO-sprite_diaper_alt'].skeleton} />
        <skinnedMesh geometry={nodes['GEO-sprite_eyebrows'].geometry} material={materials['sprite.eyebrows']} skeleton={nodes['GEO-sprite_eyebrows'].skeleton} />
        <skinnedMesh geometry={nodes['GEO-sprite_eyebrowsevil'].geometry} material={materials['sprite.eyebrows']} skeleton={nodes['GEO-sprite_eyebrowsevil'].skeleton} />
        <skinnedMesh geometry={nodes['GEO-sprite_eyedotL'].geometry} material={materials['sprite.highlights']} skeleton={nodes['GEO-sprite_eyedotL'].skeleton} />
        <skinnedMesh geometry={nodes['GEO-sprite_eyedotR'].geometry} material={materials['sprite.highlights']} skeleton={nodes['GEO-sprite_eyedotR'].skeleton} />
        <skinnedMesh geometry={nodes['GEO-sprite_teeth_bot_deformer'].geometry} material={nodes['GEO-sprite_teeth_bot_deformer'].material} skeleton={nodes['GEO-sprite_teeth_bot_deformer'].skeleton} />
        <skinnedMesh geometry={nodes['GEO-sprite_teeth_top_deformer'].geometry} material={nodes['GEO-sprite_teeth_top_deformer'].material} skeleton={nodes['GEO-sprite_teeth_top_deformer'].skeleton} />
        <skinnedMesh geometry={nodes['GEO-sprite_tongue'].geometry} material={materials['sprite.tongue']} skeleton={nodes['GEO-sprite_tongue'].skeleton} />
        <skinnedMesh name="GEO-sprite_body_arms" geometry={nodes['GEO-sprite_body_arms'].geometry} material={materials['sprite.skin.001']} skeleton={nodes['GEO-sprite_body_arms'].skeleton} morphTargetDictionary={nodes['GEO-sprite_body_arms'].morphTargetDictionary} morphTargetInfluences={nodes['GEO-sprite_body_arms'].morphTargetInfluences} />
        <skinnedMesh name="GEO-sprite_body_head_rig_helper" geometry={nodes['GEO-sprite_body_head_rig_helper'].geometry} material={nodes['GEO-sprite_body_head_rig_helper'].material} skeleton={nodes['GEO-sprite_body_head_rig_helper'].skeleton} morphTargetDictionary={nodes['GEO-sprite_body_head_rig_helper'].morphTargetDictionary} morphTargetInfluences={nodes['GEO-sprite_body_head_rig_helper'].morphTargetInfluences} />
        <skinnedMesh name="GEO-sprite_body_legs" geometry={nodes['GEO-sprite_body_legs'].geometry} material={materials['sprite.skin.001']} skeleton={nodes['GEO-sprite_body_legs'].skeleton} morphTargetDictionary={nodes['GEO-sprite_body_legs'].morphTargetDictionary} morphTargetInfluences={nodes['GEO-sprite_body_legs'].morphTargetInfluences} />
        <skinnedMesh name="GEO-sprite_body_torso" geometry={nodes['GEO-sprite_body_torso'].geometry} material={materials['sprite.skin.001']} skeleton={nodes['GEO-sprite_body_torso'].skeleton} morphTargetDictionary={nodes['GEO-sprite_body_torso'].morphTargetDictionary} morphTargetInfluences={nodes['GEO-sprite_body_torso'].morphTargetInfluences} />
        <mesh geometry={nodes['Data_GEO-sprite_teeth_btm_sharp'].geometry} material={materials['sprite.teeth']} />
        <mesh geometry={nodes['Data_GEO-sprite_teeth_btm_sharp_1'].geometry} material={materials['sprite.gums']} />
        <mesh geometry={nodes['Data_GEO-sprite_teeth_top_sharp'].geometry} material={materials['sprite.teeth']} />
        <mesh geometry={nodes['Data_GEO-sprite_teeth_top_sharp_1'].geometry} material={materials['sprite.gums']} />
        <mesh name="Data_GEO-sprite_teeth_btm" geometry={nodes['Data_GEO-sprite_teeth_btm'].geometry} material={materials['sprite.teeth']} morphTargetDictionary={nodes['Data_GEO-sprite_teeth_btm'].morphTargetDictionary} morphTargetInfluences={nodes['Data_GEO-sprite_teeth_btm'].morphTargetInfluences} />
        <mesh name="Data_GEO-sprite_teeth_btm_1" geometry={nodes['Data_GEO-sprite_teeth_btm_1'].geometry} material={materials['sprite.gums']} morphTargetDictionary={nodes['Data_GEO-sprite_teeth_btm_1'].morphTargetDictionary} morphTargetInfluences={nodes['Data_GEO-sprite_teeth_btm_1'].morphTargetInfluences} />
        <mesh name="Data_GEO-sprite_teeth_btm_square" geometry={nodes['Data_GEO-sprite_teeth_btm_square'].geometry} material={materials['sprite.teeth']} morphTargetDictionary={nodes['Data_GEO-sprite_teeth_btm_square'].morphTargetDictionary} morphTargetInfluences={nodes['Data_GEO-sprite_teeth_btm_square'].morphTargetInfluences} />
        <mesh name="Data_GEO-sprite_teeth_btm_square_1" geometry={nodes['Data_GEO-sprite_teeth_btm_square_1'].geometry} material={materials['sprite.gums']} morphTargetDictionary={nodes['Data_GEO-sprite_teeth_btm_square_1'].morphTargetDictionary} morphTargetInfluences={nodes['Data_GEO-sprite_teeth_btm_square_1'].morphTargetInfluences} />
        <mesh name="Data_GEO-sprite_teeth_top" geometry={nodes['Data_GEO-sprite_teeth_top'].geometry} material={materials['sprite.teeth']} morphTargetDictionary={nodes['Data_GEO-sprite_teeth_top'].morphTargetDictionary} morphTargetInfluences={nodes['Data_GEO-sprite_teeth_top'].morphTargetInfluences} />
        <mesh name="Data_GEO-sprite_teeth_top_1" geometry={nodes['Data_GEO-sprite_teeth_top_1'].geometry} material={materials['sprite.gums']} morphTargetDictionary={nodes['Data_GEO-sprite_teeth_top_1'].morphTargetDictionary} morphTargetInfluences={nodes['Data_GEO-sprite_teeth_top_1'].morphTargetInfluences} />
        <mesh name="Data_GEO-sprite_teeth_top_square" geometry={nodes['Data_GEO-sprite_teeth_top_square'].geometry} material={materials['sprite.teeth']} morphTargetDictionary={nodes['Data_GEO-sprite_teeth_top_square'].morphTargetDictionary} morphTargetInfluences={nodes['Data_GEO-sprite_teeth_top_square'].morphTargetInfluences} />
        <mesh name="Data_GEO-sprite_teeth_top_square_1" geometry={nodes['Data_GEO-sprite_teeth_top_square_1'].geometry} material={materials['sprite.gums']} morphTargetDictionary={nodes['Data_GEO-sprite_teeth_top_square_1'].morphTargetDictionary} morphTargetInfluences={nodes['Data_GEO-sprite_teeth_top_square_1'].morphTargetInfluences} />
        <skinnedMesh geometry={nodes['Data_GEO-sprite_body_head'].geometry} material={materials['sprite.head']} skeleton={nodes['Data_GEO-sprite_body_head'].skeleton} />
        <skinnedMesh geometry={nodes['Data_GEO-sprite_body_head_1'].geometry} material={materials['sprite.mouth_inner']} skeleton={nodes['Data_GEO-sprite_body_head_1'].skeleton} />
        <skinnedMesh geometry={nodes['Data_GEO-sprite_capmelted'].geometry} material={materials['sprite.cap_melted']} skeleton={nodes['Data_GEO-sprite_capmelted'].skeleton} />
        <skinnedMesh geometry={nodes['Data_GEO-sprite_capmelted_1'].geometry} material={materials['sprite.cap_inside']} skeleton={nodes['Data_GEO-sprite_capmelted_1'].skeleton} />
        <skinnedMesh name="Data_GEO-sprite_cap" geometry={nodes['Data_GEO-sprite_cap'].geometry} material={materials['sprite.cap']} skeleton={nodes['Data_GEO-sprite_cap'].skeleton} morphTargetDictionary={nodes['Data_GEO-sprite_cap'].morphTargetDictionary} morphTargetInfluences={nodes['Data_GEO-sprite_cap'].morphTargetInfluences} />
        <skinnedMesh name="Data_GEO-sprite_cap_1" geometry={nodes['Data_GEO-sprite_cap_1'].geometry} material={materials['sprite.cap_inside']} skeleton={nodes['Data_GEO-sprite_cap_1'].skeleton} morphTargetDictionary={nodes['Data_GEO-sprite_cap_1'].morphTargetDictionary} morphTargetInfluences={nodes['Data_GEO-sprite_cap_1'].morphTargetInfluences} />
        <skinnedMesh name="Data_GEO-sprite_eyeL" geometry={nodes['Data_GEO-sprite_eyeL'].geometry} material={materials['sprite.eyes']} skeleton={nodes['Data_GEO-sprite_eyeL'].skeleton} morphTargetDictionary={nodes['Data_GEO-sprite_eyeL'].morphTargetDictionary} morphTargetInfluences={nodes['Data_GEO-sprite_eyeL'].morphTargetInfluences} />
        <skinnedMesh name="Data_GEO-sprite_eyeL_1" geometry={nodes['Data_GEO-sprite_eyeL_1'].geometry} material={materials['sprite.pupils']} skeleton={nodes['Data_GEO-sprite_eyeL_1'].skeleton} morphTargetDictionary={nodes['Data_GEO-sprite_eyeL_1'].morphTargetDictionary} morphTargetInfluences={nodes['Data_GEO-sprite_eyeL_1'].morphTargetInfluences} />
        <skinnedMesh name="Data_GEO-sprite_eyeR" geometry={nodes['Data_GEO-sprite_eyeR'].geometry} material={materials['sprite.eyes']} skeleton={nodes['Data_GEO-sprite_eyeR'].skeleton} morphTargetDictionary={nodes['Data_GEO-sprite_eyeR'].morphTargetDictionary} morphTargetInfluences={nodes['Data_GEO-sprite_eyeR'].morphTargetInfluences} />
        <skinnedMesh name="Data_GEO-sprite_eyeR_1" geometry={nodes['Data_GEO-sprite_eyeR_1'].geometry} material={materials['sprite.pupils']} skeleton={nodes['Data_GEO-sprite_eyeR_1'].skeleton} morphTargetDictionary={nodes['Data_GEO-sprite_eyeR_1'].morphTargetDictionary} morphTargetInfluences={nodes['Data_GEO-sprite_eyeR_1'].morphTargetInfluences} />
      </group>
      <mesh geometry={nodes['GEO-sprite_body_headeyes_closed'].geometry} material={materials['sprite.skin.001']} />
      <primitive object={nodes.Spine} />
      <primitive object={nodes['PRP-Head']} />
      <primitive object={nodes['P-GrabL']} />
      <primitive object={nodes.Properties_Character_Sprite} />
      <primitive object={nodes.Eyelid_Lower1L} />
      <primitive object={nodes.Eyelid_Upper1L} />
      <primitive object={nodes['ROOT-EarL']} />
      <primitive object={nodes['P-ACT-MouthCornerL']} />
      <primitive object={nodes.Teeth_Top_Root} />
      <primitive object={nodes.OuterLip_Upper2L} />
      <primitive object={nodes.OuterLip_Upper1L} />
      <primitive object={nodes.OuterLip_Upper} />
      <primitive object={nodes['P-CTR-CheekPuffL']} />
      <primitive object={nodes.Cheek1L} />
      <primitive object={nodes['STR-Head_Top']} />
      <primitive object={nodes['STR-I-Lip_Bottom1']} />
      <primitive object={nodes['STR-I-Lip_Top1']} />
      <primitive object={nodes['P-GrabR']} />
      <primitive object={nodes.Eyelid_Lower1R} />
      <primitive object={nodes.Eyelid_Upper1R} />
      <primitive object={nodes['ROOT-EarR']} />
      <primitive object={nodes['P-ACT-MouthCornerR']} />
      <primitive object={nodes.OuterLip_Upper2R} />
      <primitive object={nodes.OuterLip_Upper1R} />
      <primitive object={nodes['P-CTR-CheekPuffR']} />
      <primitive object={nodes.Cheek1R} />
      <primitive object={nodes['P-Empty1L']} />
      <primitive object={nodes['P-Empty1R']} />
      <primitive object={nodes['P-Empty2L']} />
      <primitive object={nodes['P-Empty2R']} />
      <primitive object={nodes['LTC-MeltingCap1']} />
      <primitive object={nodes['LTC-MeltingCap3']} />
      <primitive object={nodes['LTC-MeltingCap2']} />
    </group>
  )
}

useGLTF.preload('/sprite.glb')
